export const GET_NOW_PLAYING = "GET_NOW_PLAYING";
export const GET_UPCOMING = "GET_UPCOMING";
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const GET_RECOMMENDATIONS = "GET_RECOMMENDATIONS";
export const GET_MOVIE_CREDITS = "GET_MOVIE_CREDITS";
export const GET_MOVIE_SEARCH = "GET_MOVIE_SEARCH";

export const GET_PERSON_DETAILS = "GET_PERSON_DETAILS";
export const GET_PERSON_CREDITS = "GET_PERSON_CREDITS";
export const GET_POPULAR_PERSONS = "GET_POPULAR_PERSONS";
export const GET_PERSON_SEARCH = "GET_PERSON_SEARCH";

export const LOADING = "LOADING";
export const LOADING_DETAILS = "LOADING_DETAILS";
export const LOADING_CREDITS = "LOADING_CREDITS";
